import { createEnv } from '@t3-oss/env-nextjs';
import { z } from 'zod/v4';

export const serverEnv = createEnv({
  server: {
    NODE_ENV: z.enum(['development', 'test', 'production']).default('development'),
    WAHA_BASE_URL: z.url().default('http://localhost:3000/api'),
    WAHA_API_KEY: z.string().min(16),
    WAHA_TIMEOUT_MS: z.coerce.number().int().positive().default(10_000),
    WAHA_DEFAULT_SESSION: z.string().default('default'),
    WAHA_WEBHOOK_SECRET: z.string().min(8).optional(),
    WAHA_WEBHOOK_URL: z.string().url().optional(),
    WAHA_CONTACTS_DB_PATH: z.string().optional(),
    OFTAGENDA_BOOKING_URL: z.string().url().default("https://agenda.oftleonardo.com.br/agendar"),
    STRIPE_PRIVATE_KEY: z.string().min(8).optional(),
    OPENAI_API_KEY: z.string().min(8).optional(),
    OPENAI_BASE_URL: z.string().url().optional(),
    FOX_OPENAI_MODEL: z.string().min(2).default('gpt-4.1-nano'),
    FOX_MAX_OUTPUT_TOKENS: z.coerce.number().int().positive().max(300).default(140),
    FOX_TEMPERATURE: z.coerce.number().min(0).max(1.2).default(0.55),
    FOX_REQUEST_TIMEOUT_MS: z.coerce.number().int().positive().max(15_000).default(4_000),
  },
  skipValidation: !!process.env.SKIP_ENV_VALIDATION,
  emptyStringAsUndefined: true,
  experimental__runtimeEnv: {
    NODE_ENV: process.env.NODE_ENV,
    WAHA_BASE_URL: process.env.WAHA_BASE_URL,
    WAHA_API_KEY: process.env.WAHA_API_KEY,
    WAHA_TIMEOUT_MS: process.env.WAHA_TIMEOUT_MS,
    WAHA_DEFAULT_SESSION: process.env.WAHA_DEFAULT_SESSION,
    WAHA_WEBHOOK_SECRET: process.env.WAHA_WEBHOOK_SECRET,
    WAHA_WEBHOOK_URL: process.env.WAHA_WEBHOOK_URL,
    WAHA_CONTACTS_DB_PATH: process.env.WAHA_CONTACTS_DB_PATH,
    OFTAGENDA_BOOKING_URL: process.env.OFTAGENDA_BOOKING_URL,
    STRIPE_PRIVATE_KEY: process.env.STRIPE_PRIVATE_KEY,
    OPENAI_API_KEY: process.env.OPENAI_API_KEY,
    OPENAI_BASE_URL: process.env.OPENAI_BASE_URL,
    FOX_OPENAI_MODEL: process.env.FOX_OPENAI_MODEL,
    FOX_MAX_OUTPUT_TOKENS: process.env.FOX_MAX_OUTPUT_TOKENS,
    FOX_TEMPERATURE: process.env.FOX_TEMPERATURE,
    FOX_REQUEST_TIMEOUT_MS: process.env.FOX_REQUEST_TIMEOUT_MS,
  },
});
